In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.16.1


#### Tensor Constant

In [3]:
tf_const = tf.constant(42)
tf_const

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [4]:
tf_const_1 = tf.constant(1,dtype=tf.int64)
tf_const_1

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [5]:
tf_const_x = tf.constant([[4,2],[9,5]])
print(tf_const_x)

tf.Tensor(
[[4 2]
 [9 5]], shape=(2, 2), dtype=int32)


In [6]:
print(tf_const_x.shape)
print(tf_const.shape)
print(tf_const_1.shape)

(2, 2)
()
()


Commonly used method is to generate constant tf.ones and tf.zeros like of numpy np.ones and  np.zeros

In [7]:
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [8]:
print(tf.zeros(shape=(3,2)))

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [9]:
import tensorflow as tf

const1 = tf.constant([[1,2,3],[1,2,3]])
const2 = tf.constant([[3,4,5],[3,4,5]])
result = tf.add(const1,const2)
print(result)

tf.Tensor(
[[4 6 8]
 [4 6 8]], shape=(2, 3), dtype=int32)


#### Random Constant

In [10]:
tf.random.normal(shape=(2,2),mean=0,stddev=1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.64951336,  0.0491032 ],
       [-0.35349748, -0.1206889 ]], dtype=float32)>

In [11]:
tf.random.uniform(shape=(2,2),minval=0, maxval=10,dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [8, 4]])>

In [12]:
# Variable
# A special tensor that is used to store variable values and needs to be initialized with some values

# Declaring variables
var0 = 24
var1 = tf.Variable(42)
var2 = tf.Variable([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
var0,var1,var2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(4, 3) dtype=int32, numpy=
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])>)

In [13]:
float_var64 = tf.Variable(89,dtype= tf.float64)
float_var64.dtype

tf.float64

In [14]:
var_reassign = tf.Variable(89)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=89>

In [15]:
var_reassign.assign(99)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=99>

In [16]:
initial_value = tf.random.normal(shape=(2,2))
a = tf.Variable(initial_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.34570026, 1.6046438 ],
       [0.8677049 , 0.9635867 ]], dtype=float32)>


In [17]:
new_value = tf.random.normal(shape=(2,2))
a.assign(new_value)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[-0.30995533, -2.3634913 ],
       [-1.5973351 , -1.2289274 ]], dtype=float32)>

In [18]:
added_value = tf.random.normal(shape=(2,2))
a.assign_add(added_value)

print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.6786984, -1.3770669],
       [-0.8122605, -0.8850707]], dtype=float32)>


#### Tensor shaping

In [24]:
tensor = tf.Variable([[0,1,2],[1,4,5],[6,7,8],[9,10,11]])
print(tensor.shape)

(4, 3)


In [20]:
tensor1 = tf.reshape(tensor,[2,6])
tensor2 = tf.reshape(tensor,[1,12])
tensor1

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  1,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])>

In [21]:
tensor2

<tf.Tensor: shape=(1, 12), dtype=int32, numpy=array([[ 0,  1,  2,  1,  4,  5,  6,  7,  8,  9, 10, 11]])>

#### Rank of a tensor
The rank of a tensor is the number of dimensions it has, that is, the number of indices that are required to specify any particular element of that tensor

In [25]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [27]:
tensor3 = tensor[0,2]
tensor3

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [28]:
# Casting tensor to numpy or python variable
print(tensor.numpy())

[[ 0  1  2]
 [ 1  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [29]:
print(tensor[0,2].numpy())

2


In [30]:
# Finding the size (number of elements ) of a tensor
tensor_size = tf.size(input=tensor).numpy()
tensor_size

12

In [31]:
tensor3.dtype

tf.int32

In [32]:
# mathematical operations
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
c = a + b
d = tf.square(c)
e = tf.exp(c)
print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[ 1.6016151  -0.5064629 ]
 [-0.50865984 -0.8149452 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 1.916842   -1.1450461 ]
 [-0.61893576 -2.5319867 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 3.518457  -1.651509 ]
 [-1.1275957 -3.346932 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[12.3795395  2.727482 ]
 [ 1.271472  11.201953 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[33.732338    0.19176032]
 [ 0.32381088  0.03519216]], shape=(2, 2), dtype=float32)


In [33]:
tensor*tensor

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[  0,   1,   4],
       [  1,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121]])>

In [34]:
tensor4 = tensor*4
print(tensor)

<tf.Variable 'Variable:0' shape=(4, 3) dtype=int32, numpy=
array([[ 0,  1,  2],
       [ 1,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])>


In [35]:
print(tensor4)

tf.Tensor(
[[ 0  4  8]
 [ 4 16 20]
 [24 28 32]
 [36 40 44]], shape=(4, 3), dtype=int32)


In [36]:
# Transpose of Matrix 
matrix_u = tf.constant([[3,4,5]])
matrix_v = tf.constant([[1,2,1]])

tf.matmul(matrix_u,tf.transpose(a=matrix_v))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[16]])>

In [37]:
tf.cast(tensor1, dtype=tf.int32)

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  1,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])>

In [38]:
j = tf.cast(tf.constant(4.9),dtype=tf.int32)
j

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [39]:
## Ragged Tensor tensor with varying dimensions

ragged = tf.ragged.constant([[5,2,6,7],[],[4,10,7],[8],[6,7]])
print(ragged)
print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])

<tf.RaggedTensor [[5, 2, 6, 7], [], [4, 10, 7], [8], [6, 7]]>
tf.Tensor([5 2 6 7], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([ 4 10  7], shape=(3,), dtype=int32)
tf.Tensor([8], shape=(1,), dtype=int32)
tf.Tensor([6 7], shape=(2,), dtype=int32)


In [40]:
varx = [1,3,5,7,11]
vary = 5
varz = tf.math.squared_difference(varx,vary)
varz

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([16,  4,  0,  4, 36])>

In [41]:
# Reduced mean column vise or particular row wise
numbers = tf.constant([[4.,5.],[7.,3.]])

In [42]:
tf.reduce_mean(input_tensor=numbers)

<tf.Tensor: shape=(), dtype=float32, numpy=4.75>

In [43]:
tf.reduce_mean(input_tensor=numbers, axis=0) #across columns

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5.5, 4. ], dtype=float32)>

In [45]:
# keep dims = true
tf.reduce_mean(input_tensor=numbers, axis=0, keepdims=True)

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[5.5, 4. ]], dtype=float32)>

In [46]:
tf.reduce_mean(input_tensor=numbers, axis=1, keepdims=True)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[4.5],
       [5. ]], dtype=float32)>

In [47]:
## Generating tensors with random value
tf.random.normal(shape=(3,2),mean=10,stddev=2, dtype=tf.float32, seed=None, name=None)
ran = tf.random.normal(shape=(3,2),mean=10,stddev=2.0)
print(ran)

tf.Tensor(
[[ 7.3543253 11.950684 ]
 [ 9.027794   9.056572 ]
 [12.937788  10.579503 ]], shape=(3, 2), dtype=float32)


In [48]:
tf.random.uniform(shape=(2,4),minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.9489776 , 0.57078695, 0.9834596 , 0.20210135],
       [0.78473675, 0.63233864, 0.29253602, 0.5549842 ]], dtype=float32)>