In [1]:
import numpy as np
import pandas as pd
import joblib
import matplotlib.pyplot as plt

In [9]:
class Perceptron:
    def __init__(self,eta, epochs):
        self.weights = np.random.randn(3)*1e-4
        print(f'Weigths = {self.weights}')
        self.eta  = eta
        self.epochs = epochs
    
    def activationFunction(self, inputs, weights):
        z = np.dot(inputs, weights)
        return np.where(z > 0, 1, 0)
    
    def fit(self, x, y):
        self.x = x
        self.y = y
    
        x_with_bias = np.c_[self.x, -np.ones((len(self.x),1))]
        print(f"X_with_bias: \n{x_with_bias}")

        for epochs in range(self.epochs):
            print(f"for epochs: ",{epochs})
            y_hat = self.activationFunction(x_with_bias,self.weights)
            print(f'predicted values: \n {y_hat}')
            error = self.y - y_hat 
            print(f"error: \n{error}")
            self.weights = self.weights + self.eta*np.dot(x_with_bias.T, error)
            print(f"updated weights: \n {self.weights}")
            print("======================================================================================")

    def predict(self, x):
        x_with_bias = np.c_[x,-np.ones((len(self.x),1))]
        return self.activationFunction(x_with_bias,self.weights)

In [10]:
data = {"x1":[0,0,1,1],"x2":[0,1,0,1],"y":[0,0,0,1]}
And = pd.DataFrame(data)
And

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [11]:
X = And.drop("y",axis=1)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [12]:
y  = And['y']
y.to_frame()

y
0  0
1  0
2  0
3  1

In [13]:
model = Perceptron(eta = 0.5, epochs = 10)
model.fit(X,y)

Weigths = [ 8.53712668e-05 -4.62823449e-05 -7.52593229e-05]
X_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epochs:  {0}
predicted values: 
 [1 1 1 1]
error: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights: 
 [-0.49991463 -0.50004628  1.49992474]
for epochs:  {1}
predicted values: 
 [0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights: 
 [ 8.53712668e-05 -4.62823449e-05  9.99924741e-01]
for epochs:  {2}
predicted values: 
 [0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights: 
 [0.50008537 0.49995372 0.49992474]
for epochs:  {3}
predicted values: 
 [0 1 1 1]
error: 
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights: 
 [ 8.53712668e-05 -4.62823449e-05  1.49992474e+00]
for epochs:  {4}
predicted values: 
 [0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights: 
 [0.50008537 0.49995372 0.99992474]
for epochs:  {5}
predicted values: 
 

In [14]:
model.predict(X)

array([0, 0, 0, 1])

In [ ]:
#Similarly we can do it for {or,and,nor} but not for xor