In [1]:
# Implementation of Word Embedding With Keras TensorFlow
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
#sentences 
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good'
        ]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocublary space
voc_size = 10000

In [5]:
## one how encoding
one_hot_repr = [ one_hot(words,voc_size) for words in sent]
one_hot_repr

[[220, 1359, 7246, 8544],
 [220, 1359, 7246, 2666],
 [220, 5467, 7246, 2140],
 [4236, 3786, 3036, 9066, 73],
 [4236, 3786, 3036, 9066, 3028],
 [5920, 220, 7467, 7246, 389],
 [7840, 7187, 9176, 9066]]

In [32]:
 ### word embedding representation 
from tensorflow.keras.layers import Embedding, Input
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [33]:
import numpy as np

In [34]:
set_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=set_length)
print(embedded_docs)

[[   0    0    0    0  220 1359 7246 8544]
 [   0    0    0    0  220 1359 7246 2666]
 [   0    0    0    0  220 5467 7246 2140]
 [   0    0    0 4236 3786 3036 9066   73]
 [   0    0    0 4236 3786 3036 9066 3028]
 [   0    0    0 5920  220 7467 7246  389]
 [   0    0    0    0 7840 7187 9176 9066]]


In [35]:
#feature representation
dim = 10

In [36]:
model = Sequential()
model.add(Input(shape=(set_length,)))
model.add(Embedding(voc_size,dim))
model.compile('adam','mse')

In [37]:
model.summary()

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [38]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 199ms/step


array([[[ 0.02398914, -0.0372941 , -0.01450679,  0.01209409,
          0.00665301, -0.0390815 , -0.04796337, -0.0257764 ,
         -0.0034508 ,  0.04950411],
        [ 0.02398914, -0.0372941 , -0.01450679,  0.01209409,
          0.00665301, -0.0390815 , -0.04796337, -0.0257764 ,
         -0.0034508 ,  0.04950411],
        [ 0.02398914, -0.0372941 , -0.01450679,  0.01209409,
          0.00665301, -0.0390815 , -0.04796337, -0.0257764 ,
         -0.0034508 ,  0.04950411],
        [ 0.02398914, -0.0372941 , -0.01450679,  0.01209409,
          0.00665301, -0.0390815 , -0.04796337, -0.0257764 ,
         -0.0034508 ,  0.04950411],
        [ 0.02701019,  0.00388943,  0.0051275 , -0.00116401,
         -0.03983332, -0.01682008, -0.00367256, -0.00044755,
          0.01680506,  0.04459517],
        [ 0.01169322,  0.0061422 ,  0.00905909, -0.00247203,
         -0.01588911, -0.03530354, -0.04822138,  0.00276655,
          0.02710073, -0.0020329 ],
        [-0.03936749,  0.00147427,  0.01528037,  0.0

In [45]:
embedded_docs[0]

array([   0,    0,    0,    0,  220, 1359, 7246, 8544])

In [47]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step


array([[[ 0.02398914, -0.0372941 , -0.01450679,  0.01209409,
          0.00665301, -0.0390815 , -0.04796337, -0.0257764 ,
         -0.0034508 ,  0.04950411],
        [ 0.02398914, -0.0372941 , -0.01450679,  0.01209409,
          0.00665301, -0.0390815 , -0.04796337, -0.0257764 ,
         -0.0034508 ,  0.04950411],
        [ 0.02398914, -0.0372941 , -0.01450679,  0.01209409,
          0.00665301, -0.0390815 , -0.04796337, -0.0257764 ,
         -0.0034508 ,  0.04950411],
        [ 0.02398914, -0.0372941 , -0.01450679,  0.01209409,
          0.00665301, -0.0390815 , -0.04796337, -0.0257764 ,
         -0.0034508 ,  0.04950411],
        [ 0.02701019,  0.00388943,  0.0051275 , -0.00116401,
         -0.03983332, -0.01682008, -0.00367256, -0.00044755,
          0.01680506,  0.04459517],
        [ 0.01169322,  0.0061422 ,  0.00905909, -0.00247203,
         -0.01588911, -0.03530354, -0.04822138,  0.00276655,
          0.02710073, -0.0020329 ],
        [-0.03936749,  0.00147427,  0.01528037,  0.0