In [1]:
from sklearn.datasets import load_iris

In [2]:
dataset = load_iris()

In [3]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [4]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.DataFrame(dataset.data, columns=dataset.feature_names)

In [7]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

## Appending target to the dataset

In [8]:
df['target'] = dataset.target

In [9]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

## Binary Classification

In [10]:
df_bin_cl = df[df['target']!=2]

In [11]:
df_bin_cl.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

## Independent and dependent feature

In [12]:
X = df_bin_cl.iloc[:,:-1]
y = df_bin_cl.iloc[:,-1]

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
classifier = LogisticRegression()

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [16]:
classifier.fit(X_train,y_train)

LogisticRegression()

In [17]:
## Prediction
y_pred = classifier.predict(X_test)

In [18]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1])

In [19]:
##Confusion Matrix, Accuracy Score, Classification report
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [20]:
confusion_matrix(y_pred,y_test)

array([[19,  0],
       [ 0, 14]], dtype=int64)

In [21]:
accuracy_score(y_pred,y_test)

1.0

In [22]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        14

    accuracy                           1.00        33
   macro avg       1.00      1.00      1.00        33
weighted avg       1.00      1.00      1.00        33



### HyperParameter Tuning

##### Grid Search Cross Validation

In [23]:
##Gridsearch CV
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [24]:
parameters = {'penalty':('l1','l2','elasticnet',None),'C':[1,10]}

In [25]:
clf = GridSearchCV(classifier,param_grid=parameters,cv=5)

In [26]:
## Splitting of train data to validation data
clf.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10],
                         'penalty': ('l1', 'l2', 'elasticnet', None)})

In [27]:
clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [28]:
classifier = LogisticRegression(C=1,penalty='l2')

In [29]:
classifier.fit(X_train,y_train)

LogisticRegression(C=1)

In [30]:
y_pred = classifier.predict(X_test)

In [31]:
print(classification_report(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        14

    accuracy                           1.00        33
   macro avg       1.00      1.00      1.00        33
weighted avg       1.00      1.00      1.00        33

[[19  0]
 [ 0 14]]
1.0


##### Randomized Search Cross Validation

In [32]:
from sklearn.model_selection import RandomizedSearchCV

In [33]:
random_clf = RandomizedSearchCV(LogisticRegression(),param_distributions=parameters)

In [34]:
random_clf.fit(X_train,y_train)

RandomizedSearchCV(estimator=LogisticRegression(),
                   param_distributions={'C': [1, 10],
                                        'penalty': ('l1', 'l2', 'elasticnet',
                                                    None)})

In [35]:
random_clf.best_params_

{'penalty': 'l2', 'C': 1}

In [36]:
classifier = LogisticRegression(C=1,penalty='l2')

In [37]:
classifier.fit(X_train,y_train)

LogisticRegression(C=1)

In [38]:
y_pred = classifier.predict(X_test)

In [39]:
print(classification_report(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        14

    accuracy                           1.00        33
   macro avg       1.00      1.00      1.00        33
weighted avg       1.00      1.00      1.00        33

[[19  0]
 [ 0 14]]
1.0


In [40]:
print(classifier.predict_proba(X_test))

[[0.00144397 0.99855603]
 [0.01745215 0.98254785]
 [0.00359633 0.99640367]
 [0.96426787 0.03573213]
 [0.93474767 0.06525233]
 [0.96669519 0.03330481]
 [0.99197521 0.00802479]
 [0.03413528 0.96586472]
 [0.97021318 0.02978682]
 [0.97500261 0.02499739]
 [0.94874463 0.05125537]
 [0.95431635 0.04568365]
 [0.00502564 0.99497436]
 [0.98309085 0.01690915]
 [0.01045247 0.98954753]
 [0.97787998 0.02212002]
 [0.00251112 0.99748888]
 [0.00154214 0.99845786]
 [0.96994373 0.03005627]
 [0.95517443 0.04482557]
 [0.00835383 0.99164617]
 [0.02377754 0.97622246]
 [0.95342874 0.04657126]
 [0.98084186 0.01915814]
 [0.0288064  0.9711936 ]
 [0.97695936 0.02304064]
 [0.97877889 0.02122111]
 [0.01705948 0.98294052]
 [0.96439212 0.03560788]
 [0.0018038  0.9981962 ]
 [0.96390162 0.03609838]
 [0.97429961 0.02570039]
 [0.00915585 0.99084415]]


## Multi-Class Classification
- One versue Rest
- Multinomial

In [52]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression

#define dataset
X,y = make_classification(n_samples = 1000, n_features=10, n_informative=5, n_redundant=5, n_classes=3,random_state=42) 

In [56]:
model = LogisticRegression(multi_class='multinomial', solver='lbfgs')

In [57]:
#train_test_split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20,random_state=42)

In [58]:
model.fit(X_train,y_train)

LogisticRegression(multi_class='multinomial')

In [59]:
y_pred = model.predict(X_test)

In [60]:
y_pred

array([1, 0, 1, 1, 0, 0, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 2, 1, 2, 2,
       0, 0, 0, 0, 1, 2, 2, 0, 1, 0, 2, 2, 1, 1, 0, 1, 1, 0, 0, 2, 2, 2,
       2, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 2, 1, 0, 1, 1, 0, 0, 2, 1, 2,
       0, 0, 2, 2, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 2, 2, 1, 2, 2, 2, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 2, 2, 2, 1, 0, 1, 1, 2, 1, 1, 1, 0, 1,
       2, 0, 0, 2, 1, 2, 0, 1, 2, 1, 2, 2, 1, 0, 0, 0, 1, 2, 0, 2, 0, 0,
       2, 1, 0, 1, 0, 1, 2, 1, 2, 2, 1, 2, 2, 0, 2, 2, 1, 1, 0, 0, 0, 2,
       1, 0, 1, 0, 0, 1, 2, 2, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 1, 1, 0,
       1, 1, 2, 0, 1, 1, 0, 0, 2, 2, 1, 2, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1])

In [61]:
y_prob_pred = model.predict_proba(X_test)

In [62]:
y_prob_pred

array([[8.36843539e-02, 6.54955336e-01, 2.61360310e-01],
       [4.41803863e-01, 2.76936172e-01, 2.81259965e-01],
       [2.48904612e-01, 3.90832645e-01, 3.60262743e-01],
       [4.27466100e-03, 7.74532773e-01, 2.21192566e-01],
       [7.66800858e-01, 4.21131814e-02, 1.91085961e-01],
       [9.82261731e-01, 4.32996016e-05, 1.76949696e-02],
       [5.89332987e-02, 5.34411667e-01, 4.06655034e-01],
       [3.62642490e-01, 9.98390844e-02, 5.37518426e-01],
       [1.49329956e-01, 3.43276288e-01, 5.07393755e-01],
       [3.10578993e-01, 1.62701880e-01, 5.26719127e-01],
       [4.59691746e-01, 1.41122921e-01, 3.99185333e-01],
       [9.27928048e-01, 3.33485272e-03, 6.87370990e-02],
       [5.66794643e-01, 1.09324631e-02, 4.22272894e-01],
       [9.30528426e-01, 3.88682416e-03, 6.55847496e-02],
       [7.60620347e-01, 3.83211840e-02, 2.01058469e-01],
       [8.18101527e-01, 8.72036507e-03, 1.73178108e-01],
       [3.52765912e-01, 1.02784771e-01, 5.44449317e-01],
       [5.52720074e-02, 4.21720

In [63]:
from sklearn.metrics import confusion_matrix,accuracy_score, classification_report
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[52  5 11]
 [ 8 47 17]
 [ 8 13 39]]
0.69
              precision    recall  f1-score   support

           0       0.76      0.76      0.76        68
           1       0.72      0.65      0.69        72
           2       0.58      0.65      0.61        60

    accuracy                           0.69       200
   macro avg       0.69      0.69      0.69       200
weighted avg       0.69      0.69      0.69       200

